import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary":                  "#705d00",
        "primary-container":        "#ffd700",
        "primary-fixed":            "#ffe16d",
        "primary-fixed-dim":        "#e9c400",
        "on-primary":               "#ffffff",
        "on-primary-container":     "#705e00",
        "on-primary-fixed":         "#221b00",
        "on-primary-fixed-variant": "#544600",
        "background":               "#fbf9f8",
        "surface":                  "#fbf9f8",
        "surface-bright":           "#fbf9f8",
        "surface-dim":              "#dcd9d9",
        "surface-variant":          "#e4e2e1",
        "surface-container":        "#f0eded",
        "surface-container-low":    "#f6f3f2",
        "surface-container-high":   "#eae8e7",
        "surface-container-highest":"#e4e2e1",
        "surface-container-lowest": "#ffffff",
        "on-surface":               "#1b1c1c",
        "on-surface-variant":       "#4d4732",
        "on-background":            "#1b1c1c",
        "secondary":                "#5f5e5e",
        "secondary-container":      "#e4e2e1",
        "on-secondary":             "#ffffff",
        "tertiary":                 "#5d5f5f",
        "tertiary-container":       "#d9dada",
        "on-tertiary":              "#ffffff",
        "outline":                  "#7e775f",
        "outline-variant":          "#d0c6ab",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "on-error":                 "#ffffff",
        "on-error-container":       "#93000a",
        "inverse-surface":          "#303030",
        "inverse-on-surface":       "#f3f0f0",
        "inverse-primary":          "#e9c400",
      },
      fontFamily: {
        "headline-lg":      ['"Source Serif 4"', "Georgia", "serif"],
        "headline-md":      ['"Source Serif 4"', "Georgia", "serif"],
        "headline-sm":      ['"Source Serif 4"', "Georgia", "serif"],
        "body-lg":          ['"Public Sans"', "system-ui", "sans-serif"],
        "body-md":          ['"Public Sans"', "system-ui", "sans-serif"],
        "label-md":         ['"Public Sans"', "system-ui", "sans-serif"],
        "label-mono":       ['"JetBrains Mono"', "ui-monospace", "monospace"],
        "data-md":          ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg":     ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md":     ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md":    ["12px", { lineHeight: "1",   fontWeight: "700",  letterSpacing: "0.05em" }],
        "label-mono":  ["11px", { lineHeight: "1",   fontWeight: "500",  letterSpacing: "0.02em" }],
        "data-md":     ["13px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        "ink-stroke": {
          "0%":   { strokeDashoffset: "120" },
          "60%":  { strokeDashoffset: "0" },
          "100%": { strokeDashoffset: "-120" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
      },
      animation: {
        "ink-stroke": "ink-stroke 1.6s cubic-bezier(0.2, 0.8, 0.2, 1) infinite",
        "fade-in":    "fade-in 240ms cubic-bezier(0.2, 0.8, 0.2, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
